In [2]:
import cftime
import matplotlib.pyplot as plt
import xarray as xr

import geocat.comp as gc
import geocat.datafiles as gdf
import numpy as np

In [3]:
ds = xr.open_dataset(gdf.get('netcdf_files/atm.20C.hourly6-1990-1995-TS.nc'))
dset = ds.isel(member_id=0)  # select one model from the ensemble

temp = dset.TS  # surface temperature data

In [4]:
non_custom = gc.climatology_average(temp, freq='season')
non_custom

<xarray.DataArray (season: 4)>
array([299.85390225, 300.97901336, 299.88809552, 300.06040999])
Coordinates:
  * season   (season) object 'DJF' 'JJA' 'MAM' 'SON'
Attributes:
    long_name:  Surface temperature (radiative)
    units:      K

In [11]:
dset = temp
freq = 'season'
custom_seasons = ['DJF', 'MAM', 'JJA', 'SON']
time_dim = None
time_coord_name = None

ds_custom = gc.climatology_average(dset, freq=freq, custom_seasons=custom_seasons)
ds_custom

<xarray.DataArray (season: 4)>
array([299.85390225, 299.88809552, 300.97901336, 300.06040999])
Coordinates:
  * season   (season) <U3 'DJF' 'MAM' 'JJA' 'SON'
Attributes:
    long_name:  Surface temperature (radiative)
    units:      K

In [12]:
non_custom.equals(ds_custom)

True

In [16]:
print(ds_custom)

<xarray.DataArray (season: 4)>
array([299.85390225, 299.88809552, 300.97901336, 300.06040999])
Coordinates:
  * season   (season) <U3 'DJF' 'MAM' 'JJA' 'SON'
Attributes:
    long_name:  Surface temperature (radiative)
    units:      K


In [17]:
print(non_custom)

<xarray.DataArray (season: 4)>
array([299.85390225, 299.88809552, 300.97901336, 300.06040999])
Coordinates:
  * season   (season) <U3 'DJF' 'MAM' 'JJA' 'SON'
Attributes:
    long_name:  Surface temperature (radiative)
    units:      K


In [11]:
def _contains_datetime_like_objects(d_arr):
    """Check if a variable contains datetime like objects (either
    np.datetime64, or cftime.datetime)"""
    return np.issubdtype(
        d_arr.dtype,
        np.datetime64) or xr.core.common.contains_cftime_datetimes(d_arr)
    
def _get_time_coordinate_info(dset, time_coord_name):
    if time_coord_name:
        time = dset[time_coord_name]
    else:
        time = dset.cf["time"]
        time_coord_name = time.name

    if not _contains_datetime_like_objects(time):
        raise ValueError(
            f"The {time_coord_name} coordinate should be either `np.datetime64` or `cftime.datetime`"
        )

    return time_coord_name

In [12]:
# Focus on anomaly now
clim = gc.climatology_average(temp,freq='season')
time_dim = _get_time_coordinate_info(temp, None)
anom = dset.groupby(f"{time_dim}.season") - clim

In [14]:
clim

<xarray.DataArray (season: 4)>
array([299.85390225, 299.88809552, 300.97901336, 300.06040999])
Coordinates:
  * season   (season) <U3 'DJF' 'MAM' 'JJA' 'SON'
Attributes:
    long_name:  Surface temperature (radiative)
    units:      K

In [20]:
[print(s) for s in anom.season.values]

DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
DJF
MAM
MAM
MAM
MAM
MAM
MAM
MAM
MAM
MAM
MAM
MAM
MAM
MAM
MAM


[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,